name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'enhancement'
    label: 'feature'
  - title: 'Fixes'
    label: 'fix'
    label: 'bug'
  - title: 'Etcetera'
    label: 'documentation'
# categories:
#   - title: 'ğŸš€ ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ ì¶”ê°€ë˜ì—ˆì–´ìš”'
#     label:
#       - 'ğŸš€ feature'
#       - 'feature'
#       - 'enhancement'
#       - 'implement'
#       - 'update'
#   - title: 'ğŸ”¨ ìì˜í•œ ë²„ê·¸ë¥¼ ìˆ˜ì •í–ˆì–´ìš”'
#     label:
#       - 'ğŸ”¨ fix'
#       - 'fix'
#       - 'bugfix'
#       - 'bug'
#   - title: 'ğŸ¬ ì½”ë“œë¥¼ ê°œì„ í–ˆì–´ìš”'
#     label:
#       - 'ğŸ“‹ docs'
#       - 'docs'
#       - 'ğŸ§¼ refactor'
#       - 'refactor'
#       - 'ğŸª„ setting'
#       - 'setting'
#       - 'ğŸ« test'
#       - 'test'
#       - 'ğŸš€ deploy'
#       - 'deploy'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentio
no-changes-template: 'There are no changes.'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
# version-resolver:
#   major:
#     labels:
#       - 'âœ¨ major'
#   minor:
#     labels:
#       - 'ğŸª„ minor'
#   patch:
#     labels:
#       - '- 'ğŸ§© patch'
#   default: patch
template: |
  ## What's Changed
  ---
  $CHANGES
  ---
  $CONTRIBUTORS
